//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTM_SUITEDEFINITION
    {
        public string ANALYSISSUITE { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> ANALYSISREQUIRED { get; set; }
    }
}
