//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTM_STANDARDSDEFINITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTM_STANDARDSDEFINITION()
        {
            this.DTM_STANDARDSASSAY = new HashSet<DTM_STANDARDSASSAY>();
            this.DTM_QAQC_BLK_STD = new HashSet<DTM_QAQC_BLK_STD>();
        }
    
        public string STANDARDID { get; set; }
        public string STANDARDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STANDARDTYPE { get; set; }
        public Nullable<byte> STANDARDACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTM_STANDARDSASSAY> DTM_STANDARDSASSAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTM_QAQC_BLK_STD> DTM_QAQC_BLK_STD { get; set; }
    }
}
