//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTM_QAQC_BLK_STD
    {
        public string CHECKID { get; set; }
        public string STANDARDID { get; set; }
        public string HOLEID { get; set; }
        public string ASSAYNAME { get; set; }
        public Nullable<double> ASSAYVALUE { get; set; }
        public int ASSAY_PRIORITY { get; set; }
        public string DESPATCHNO { get; set; }
        public string LABJOBNO { get; set; }
        public string LABCODE { get; set; }
        public string ANALYSISSUITE { get; set; }
        public string RETURNDATE { get; set; }
        public string SENDDATE { get; set; }
    
        public virtual DTM_STANDARDSDEFINITION DTM_STANDARDSDEFINITION { get; set; }
    }
}
