//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTM_QAQC_DUP
    {
        public string ID_OR { get; set; }
        public string ID_CK { get; set; }
        public string HOLEID { get; set; }
        public string PROJECTCODE { get; set; }
        public Nullable<double> SAMPFROM { get; set; }
        public Nullable<double> SAMPTO { get; set; }
        public string CHECKSTAGE { get; set; }
        public string ASSAYNAME { get; set; }
        public Nullable<double> ASSAYVALUE_OR { get; set; }
        public Nullable<double> ASSAYVALUE_CK { get; set; }
        public Nullable<double> DIFERENCIA { get; set; }
        public Nullable<double> VAR_REL { get; set; }
        public Nullable<double> AMPD { get; set; }
        public Nullable<double> PROMEDIO { get; set; }
        public Nullable<double> MPD { get; set; }
        public int PRIORITY_OR { get; set; }
        public int PRIORITY_CK { get; set; }
        public string DESPATCHNO { get; set; }
        public string LABJOBNO_OR { get; set; }
        public string LABJOBNO_CK { get; set; }
        public string LABCODE { get; set; }
        public string ANALYSISSUITE { get; set; }
        public Nullable<System.DateTime> SENDDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public string SAMPLE_DRILLTYPE { get; set; }
        public string T_MIN { get; set; }
    
        public virtual DTM_COLLAR DTM_COLLAR { get; set; }
    }
}
