//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTM_STANDARDSASSAY
    {
        public string STANDARDID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> STANDARDVALUE { get; set; }
        public Nullable<double> STANDARDDEVIATION { get; set; }
        public Nullable<double> STANDARDRANGE { get; set; }
        public Nullable<double> ACCEPTABLEMIN { get; set; }
        public Nullable<double> ACCEPTABLEMAX { get; set; }
    
        public virtual DTM_STANDARDSDEFINITION DTM_STANDARDSDEFINITION { get; set; }
    }
}
