//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace geologycmcc.Models.GeologiaQAQCModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DM_CC_SONEntities : DbContext
    {
        public DM_CC_SONEntities()
            : base("name=DM_CC_SONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DTM_COLLAR> DTM_COLLAR { get; set; }
        public virtual DbSet<DTM_QAQC_BLK_STD> DTM_QAQC_BLK_STD { get; set; }
        public virtual DbSet<DTM_QAQC_DUP> DTM_QAQC_DUP { get; set; }
        public virtual DbSet<DTM_STANDARDSASSAY> DTM_STANDARDSASSAY { get; set; }
        public virtual DbSet<DTM_STANDARDSDEFINITION> DTM_STANDARDSDEFINITION { get; set; }
        public virtual DbSet<DTM_SUITEDEFINITION> DTM_SUITEDEFINITION { get; set; }
    }
}
