using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using geologycmcc.Controllers.DataBase;
using geologycmcc.Models.GeologiaModels;
namespace geologycmcc.Controllers.Crud
{
    public class CRUDGeologia
    {
        TransaccionesGeologia tr;

        public IEnumerable<StockControlesSOND> listaControlStockSOND()
        {
            tr = new TransaccionesGeologia();
            IEnumerable<StockControlesSOND> resultado = tr.dataStockControlSOND("SELECT UTSON.STD, UTSON.DESCRIPTION, ISNULL(UTSON.[STOCKSOND], 0)STOCKGEOL, ISNULL(VALSON.[VALSOND], 0)VALIDADOSGEOL, ISNULL(RECHSON.[RECHSOND], 0)RECHAZADOSGEOL, ISNULL(STSON.[UTILIZADOSSOND], 0)[UTILIZADOSGEOL], (ISNULL(UTSON.[STOCKSOND], 0) + ISNULL(STSON.[UTILIZADOSSOND], 0)) AS[TOTALGEOL] FROM"+
             "(SELECT MIN(SD.STANDARDID) STD, MAX(DESCRIPTION) DESCRIPTION, COUNT(CHECKID) AS[STOCKSOND]FROM CHECKSAMPLE CS, STANDARDSDEFINITION SD WHERE SD.STANDARDID = CS.STANDARDID AND CHECKID NOT IN(SELECT CHECKID FROM CHECKDESPATCH) AND CS.STANDARDID in (SELECT STANDARDID FROM STANDARDSDEFDETAILS WHERE NAME = 'ST_STATUS' AND VALUE = 'ACTIVO')  GROUP BY CS.STANDARDID)UTSON"+
             "FULL OUTER JOIN(SELECT MIN(SD.STANDARDID) STD, MAX(DESCRIPTION) DESCRIPTION, COUNT(CHECKID) AS[VALSOND] FROM CHECKSAMPLE CS, STANDARDSDEFINITION SD WHERE SD.STANDARDID = CS.STANDARDID AND CHECKID NOT IN(SELECT CHECKID FROM CHECKDESPATCH) AND CHECKID  IN(SELECT CHECKID FROM CHECKDETAILS WHERE NAME = 'SA_STATE' AND VALUE = 'Preparada') AND CHECKID NOT IN(SELECT CHECKID FROM CHECKDETAILS WHERE NAME = 'PSTANDARDID') AND CS.STANDARDID in (SELECT STANDARDID FROM STANDARDSDEFDETAILS WHERE NAME = 'ST_STATUS' AND VALUE = 'ACTIVO') GROUP BY CS.STANDARDID)VALSON on VALSON.STD = UTSON.STD"+
             "FULL OUTER JOIN(SELECT MIN(SD.STANDARDID) STD, MAX(DESCRIPTION) DESCRIPTION, COUNT(CHECKID) AS[RECHSOND] FROM CHECKSAMPLE CS, STANDARDSDEFINITION SD WHERE SD.STANDARDID = CS.STANDARDID AND CHECKID NOT IN(SELECT CHECKID FROM CHECKDESPATCH) AND CHECKID  IN(SELECT CHECKID FROM CHECKDETAILS WHERE NAME = 'SA_STATE' AND VALUE = 'Rechazada') AND CHECKID NOT IN(SELECT CHECKID FROM CHECKDETAILS WHERE NAME = 'PSTANDARDID') AND CS.STANDARDID in (SELECT STANDARDID FROM STANDARDSDEFDETAILS WHERE NAME = 'ST_STATUS' AND VALUE = 'ACTIVO') GROUP BY CS.STANDARDID)RECHSON on RECHSON.STD = UTSON.STD"+
             "FULL OUTER JOIN(SELECT A.STD, COUNT(A.CHECKID) AS[UTILIZADOSSOND] FROM(SELECT distinct SD.STANDARDID STD, CS.CHECKID  FROM CHECKSAMPLE CS inner join STANDARDSDEFINITION SD on SD.STANDARDID = CS.STANDARDID INNER JOIN CHECKDESPATCH CD ON CD.CHECKID = CS.CHECKID INNER JOIN SAMPLEDESPATCH SLD ON SLD.DESPATCHNO = CD.DESPATCHNO INNER JOIN SAMPLE S ON S.SAMPLEID = SLD.SAMPLEID INNER JOIN COLLAR HL ON S.HOLEID = HL.HOLEID WHERE CS.CHECKID  IN(SELECT CHECKID FROM CHECKDESPATCH WHERE DESPATCHNO LIKE '%SGS%') AND CS.STANDARDID in (SELECT STANDARDID FROM STANDARDSDEFDETAILS WHERE NAME = 'ST_STATUS' AND VALUE = 'ACTIVO'))A GROUP BY A.STD )STSON ON STSON.STD = UTSON.STD ORDER BY STD");

            return resultado;
        }
    }
}